SELECT * FROM dbo.Recipe
SELECT * FROM dbo.Ingredient
SELECT * FROM dbo.Style
SELECT * FROM dbo.Category
SELECT * FROM dbo.Dish
SELECT * FROM dbo.RecipeStep
SELECT * FROM dbo.RecipeIngredient
SELECT * FROM dbo.RecipeStepIngredient
SELECT * FROM dbo.RecipeCategory
SELECT * FROM dbo.RecipeDish
SELECT * FROM dbo.RecipeStyle